import type { Metadata } from "next";
import localFont from "next/font/local";

import "@repo/design-system/styles/globals.css";

const Inter = localFont({
  src: "./fonts/Inter.ttf",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${Inter.variable}`}>{children}</body>
    </html>
  );
}
